# Generated by Django 4.2.21 on 2025-09-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_facility_program_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('paragraph', models.CharField(max_length=1000)),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
